# Generated by Django 3.2 on 2022-12-14 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Noticia',
            new_name='Publicacion',
        ),
        migrations.RenameField(
            model_name='publicacion',
            old_name='categoria_noticia',
            new_name='categoria_publicacion',
        ),
    ]
