# Generated by Django 3.2 on 2022-12-20 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0003_alter_recurso_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
